dist: focal
language: python
python:
  - 3.9
 
branches:
  only:
    - main
    - chz9577_dev_branch
    - develop
before_install:
  - pip install awscli  
  - pip install awsebcli  

install:
  - pip install -r CleanBites/requirements.txt

before_script:
  - python CleanBites/manage.py migrate
  - python CleanBites/manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=team5-wed-spring25 CleanBites/manage.py test
  - bash CleanBites/travis_instance_update.sh

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "us-west-2"
  app: "CleanBites-amznlnx-docker-stable"
  env: "CleanBites-amznlnx-docker-stable-env"
  bucket_name: "elasticbeanstalk-us-east-1-054037135006"
  on:
    repo: gcivil-nyu-org/team5-wed-spring25
    branch: main
  skip_cleanup: 'true'
