dist: focal
language: python
python:
  - 3.9
 
branches:
  only:
    - main
    - chz9577_dev_branch
    - develop
services:
  - docker

install:
  - pip install awscli  
  - pip install awsebcli  
  - pip install -r CleanBites/requirements.txt

script:
  - eb --version
  - black --check .
  - flake8 .
  - cd CleanBites

after_script:
  - coveralls

deploy:
  provider: script
  script: bash travis_instance_update.sh
  on:
    branch: chz9577_dev_branch

