branch-defaults:
  default:
    environment: CleanBites-production-env
environment-defaults:
  CleanBites-production-env:
    branch: null
    repository: null
global:
  application_name: CleanBites-production
  default_ec2_keyname: clean-bites
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
