branch-defaults:
  default:
    environment: CleanBites-env-production-stable
environment-defaults:
  CleanBites-env-production-stable:
    branch: null
    repository: null
global:
  application_name: CleanBites-production-stable
  default_ec2_keyname: clean-bites
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
