dist: focal
language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=team5-wed-spring25 manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  region: "us-west-2"
  app: "CleanBites"
  env: "CleanBites-env"
  bucket_name: "elasticbeanstalk-us-east-1-054037135006"
  on:
    repo: gcivil-nyu-org/team5-wed-spring25
    branch: main
  skip_cleanup: 'true'

