services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - cleanbites-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./staticfiles:/app/staticfiles

networks:
  cleanbites-network:
    driver: bridge
