services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - cleanbites-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # volumes:
    #   - ./staticfiles:/app/staticfiles
    volumes:
      - .:/app  # Mounts the entire project directory to /app in the container
  nycmap:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python _frontend/nycmap.py
    env_file:
      - .env
    networks:
      - cleanbites-network
    volumes:
      - .:/app  # Syncs local changes inside the container in real-time

networks:
  cleanbites-network:
    driver: bridge