# Generated by Django 4.2.20 on 2025-05-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0017_merge_20250428_1742"),
        ("_users", "0017_merge_20250429_1954"),
    ]

    operations = []
