# Generated by Django 4.2.20 on 2025-04-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0002_initial"),
        ("_restaurants", "0014_comment_parent"),
    ]

    operations = []
