# Generated by Django 4.2.20 on 2025-05-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0017_merge_20250501_0053"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="flagged_by",
        ),
    ]
