# Generated by Django 4.2.20 on 2025-03-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_frontend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Restaurant",
        ),
    ]
