# Generated by Django 4.2.20 on 2025-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0003_alter_customer_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="aboutme",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="fav_cuisine",
            field=models.CharField(default="", max_length=255),
        ),
    ]
