# Generated by Django 4.2.20 on 2025-04-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0015_customer_karmatotal"),
        ("_users", "0016_alter_customer_blocked_customers"),
    ]

    operations = []
