# Generated by Django 4.2.20 on 2025-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_users", "0017_merge_20250429_1954"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="aboutme",
            field=models.TextField(blank=True, null=True),
        ),
    ]
