# Generated by Django 4.2.20 on 2025-04-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("_restaurants", "0001_initial"),
        ("_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="_users.customer"
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="flagged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="_users.moderator",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="_users.customer"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="flagged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="_users.moderator",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="_restaurants.restaurant",
            ),
        ),
    ]
