# Generated by Django 4.2.20 on 2025-05-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("_restaurants", "0015_merge_0002_initial_0014_comment_parent"),
        ("_restaurants", "0016_alter_comment_k_voters"),
    ]

    operations = []
